// content/resources.js
// ─────────────────────────────────────────────
// Static seed resources — pre-curated, always vetted, always visible.
// Lecturers can update any URL via the Resource Manager in the Analytics dashboard.
// ─────────────────────────────────────────────

export const SEED_RESOURCES = [

  // ── Critical Reading (4) ─────────────────────────────────────
  {
    id: 'r001',
    type: 'video',
    embedType: 'youtube',
    title: 'How to Read Academic Texts Strategically',
    description: 'A step-by-step guide to active reading strategies for university students, covering annotation, SQ3R, and skimming techniques.',
    url: 'https://www.youtube.com/watch?v=IlU-zDU6aQ0',
    source: 'YouTube',
    duration: '9 min',
    skillTags: ['critical_reading'],
    phaseTags: [1, 2],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r002',
    type: 'article',
    embedType: 'link',
    title: 'Active Reading Strategies — OWL Purdue',
    description: 'Purdue OWL\'s comprehensive guide to active reading, including previewing, questioning, and summarising techniques.',
    url: 'https://owl.purdue.edu/owl/general_writing/academic_writing/active_reading/index.html',
    source: 'University',
    duration: '8 min read',
    skillTags: ['critical_reading'],
    phaseTags: [1],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r003',
    type: 'article',
    embedType: 'link',
    title: 'Critical Reading vs. Passive Reading',
    description: 'Explains the difference between surface-level reading and genuine critical engagement with scholarly texts.',
    url: 'https://www.skillsyouneed.com/learn/critical-reading.html',
    source: 'Other',
    duration: '6 min read',
    skillTags: ['critical_reading'],
    phaseTags: [1, 2],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r004',
    type: 'podcast',
    embedType: 'link',
    title: 'The Learning Scientists — Effective Reading Podcast',
    description: 'Researchers explain evidence-based reading strategies: spaced practice, elaborative interrogation, and retrieval.',
    url: 'https://www.learningscientists.org/learning-scientists-podcast',
    source: 'Podcast',
    duration: '25 min',
    skillTags: ['critical_reading', 'research_skills'],
    phaseTags: [1, 2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Evidence Use (4) ─────────────────────────────────────────
  {
    id: 'r005',
    type: 'video',
    embedType: 'youtube',
    title: 'Integrating Evidence into Academic Writing',
    description: 'Covers how to introduce quotes, paraphrase effectively, and signal-phrase techniques for seamless evidence integration.',
    url: 'https://www.youtube.com/watch?v=nYFuxnNFjkY',
    source: 'YouTube',
    duration: '11 min',
    skillTags: ['evidence_use'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r006',
    type: 'article',
    embedType: 'link',
    title: 'Quoting, Paraphrasing & Summarising — OWL Purdue',
    description: 'Detailed guide from Purdue OWL on when and how to quote, paraphrase, or summarise sources in academic essays.',
    url: 'https://owl.purdue.edu/owl/research_and_citation/using_research/quoting_paraphrasing_and_summarizing/index.html',
    source: 'University',
    duration: '10 min read',
    skillTags: ['evidence_use', 'citation_practice'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r007',
    type: 'pdf',
    embedType: 'pdf',
    title: 'PEEL Paragraph Structure Guide (PDF)',
    description: 'Downloadable one-page guide showing the Point–Evidence–Explain–Link paragraph model for academic writing.',
    url: 'https://www.deakin.edu.au/__data/assets/pdf_file/0007/1099605/paragraph-structure.pdf',
    source: 'University',
    duration: '1 page',
    skillTags: ['evidence_use', 'argument_structure'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r008',
    type: 'article',
    embedType: 'link',
    title: 'Using Evidence Effectively — University of Manchester',
    description: 'Academic Phrasebank guide on introducing and commenting on evidence, with sample language for every stage.',
    url: 'https://www.phrasebank.manchester.ac.uk/being-critical/',
    source: 'University',
    duration: '7 min read',
    skillTags: ['evidence_use'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Argument Structure (4) ───────────────────────────────────
  {
    id: 'r009',
    type: 'video',
    embedType: 'youtube',
    title: 'How to Write a Strong Academic Argument',
    description: 'Breaks down thesis statements, claim-evidence-reasoning chains, and counterargument techniques for essays.',
    url: 'https://www.youtube.com/watch?v=jocqkMaqBEk',
    source: 'YouTube',
    duration: '8 min',
    skillTags: ['argument_structure'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r010',
    type: 'article',
    embedType: 'link',
    title: 'The Toulmin Model of Argumentation — OWL Purdue',
    description: 'Explains the six elements of a Toulmin argument (claim, grounds, warrant, backing, qualifier, rebuttal) with examples.',
    url: 'https://owl.purdue.edu/owl/general_writing/academic_writing/logic_in_argumentative_writing/index.html',
    source: 'University',
    duration: '10 min read',
    skillTags: ['argument_structure'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r011',
    type: 'article',
    embedType: 'link',
    title: 'Writing a Thesis Statement — OWL Purdue',
    description: 'Step-by-step guide to crafting arguable, specific, and evidence-based thesis statements for academic essays.',
    url: 'https://owl.purdue.edu/owl/general_writing/the_writing_process/thesis_statement_tips/index.html',
    source: 'University',
    duration: '5 min read',
    skillTags: ['argument_structure'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r012',
    type: 'video',
    embedType: 'youtube',
    title: 'Counterargument and Rebuttal Techniques',
    description: 'A concise video walkthrough of how to acknowledge and refute counterarguments to strengthen academic essays.',
    url: 'https://www.youtube.com/watch?v=YFWm7Ot4EPc',
    source: 'YouTube',
    duration: '6 min',
    skillTags: ['argument_structure', 'critical_reading'],
    phaseTags: [3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Academic Tone (4) ────────────────────────────────────────
  {
    id: 'r013',
    type: 'pdf',
    embedType: 'pdf',
    title: 'Academic Writing Style — Manchester Academic Phrasebank (PDF)',
    description: 'Printable reference card from the University of Manchester listing formal academic phrases for all essay sections.',
    url: 'https://www.phrasebank.manchester.ac.uk/wp-content/uploads/2022/04/Academic-Phrasebank-2022-edition.pdf',
    source: 'University',
    duration: '80 pages',
    skillTags: ['academic_tone'],
    phaseTags: [1, 2, 3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r014',
    type: 'video',
    embedType: 'youtube',
    title: 'Hedging Language in Academic Writing',
    description: 'Explains why and how to use hedging expressions (may, suggest, appears to) to write with appropriate academic caution.',
    url: 'https://www.youtube.com/watch?v=J2O0yLXnhpM',
    source: 'YouTube',
    duration: '7 min',
    skillTags: ['academic_tone'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r015',
    type: 'article',
    embedType: 'link',
    title: 'Formal vs Informal Language in Academic Writing',
    description: 'Side-by-side comparisons of informal and formal register with practical rewriting exercises.',
    url: 'https://www.uefap.com/writing/writfram.htm',
    source: 'University',
    duration: '8 min read',
    skillTags: ['academic_tone'],
    phaseTags: [1, 2],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r016',
    type: 'article',
    embedType: 'link',
    title: 'Academic Writing — General Style Principles',
    description: 'RMIT University guide covering objectivity, precision, formality, and impersonal constructions in academic prose.',
    url: 'https://www.rmit.edu.au/students/study-support/study-skills/academic-writing',
    source: 'University',
    duration: '6 min read',
    skillTags: ['academic_tone', 'argument_structure'],
    phaseTags: [1, 2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Source Evaluation (4) ────────────────────────────────────
  {
    id: 'r017',
    type: 'video',
    embedType: 'youtube',
    title: 'How to Evaluate Sources — CRAAP Test Explained',
    description: 'Introduces the Currency, Relevance, Authority, Accuracy, and Purpose framework for evaluating any information source.',
    url: 'https://www.youtube.com/watch?v=yFRDsLp_h08',
    source: 'YouTube',
    duration: '5 min',
    skillTags: ['source_evaluation'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r018',
    type: 'article',
    embedType: 'link',
    title: 'The SIFT Method — Four Moves for Source Checking',
    description: 'Mike Caulfield\'s lateral reading framework: Stop, Investigate the source, Find better coverage, Trace claims.',
    url: 'https://hapgood.us/2019/06/19/sift-the-four-moves/',
    source: 'Other',
    duration: '8 min read',
    skillTags: ['source_evaluation', 'ai_literacy'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r019',
    type: 'article',
    embedType: 'link',
    title: 'Evaluating Sources of Information — OWL Purdue',
    description: 'Systematic guide to assessing print and online sources for academic use, with worked examples.',
    url: 'https://owl.purdue.edu/owl/research_and_citation/conducting_research/evaluating_sources_of_information/index.html',
    source: 'University',
    duration: '9 min read',
    skillTags: ['source_evaluation'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r020',
    type: 'video',
    embedType: 'youtube',
    title: 'Lateral Reading: How Fact-Checkers Evaluate Sources',
    description: 'Demonstrates how professional fact-checkers open multiple tabs to cross-check claims rather than reading one source deeply.',
    url: 'https://www.youtube.com/watch?v=GoQG6Tin-1E',
    source: 'YouTube',
    duration: '8 min',
    skillTags: ['source_evaluation', 'ai_literacy'],
    phaseTags: [3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Citation Practice (5) ────────────────────────────────────
  {
    id: 'r021',
    type: 'article',
    embedType: 'link',
    title: 'APA 7th Edition — OWL Purdue Complete Guide',
    description: 'The definitive web reference for APA 7th Edition formatting: in-text citations, reference lists, and formatting rules.',
    url: 'https://owl.purdue.edu/owl/research_and_citation/apa_style/apa_formatting_and_style_guide/index.html',
    source: 'University',
    duration: 'Reference',
    skillTags: ['citation_practice'],
    phaseTags: [2, 3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r022',
    type: 'video',
    embedType: 'youtube',
    title: 'APA 7th Edition: In-Text Citations Made Easy',
    description: 'Visual tutorial covering author-date format, multiple authors, direct quotes, and paraphrases in APA 7th edition.',
    url: 'https://www.youtube.com/watch?v=fDsLLuHq72c',
    source: 'YouTube',
    duration: '10 min',
    skillTags: ['citation_practice'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r023',
    type: 'article',
    embedType: 'link',
    title: 'Avoiding Plagiarism — OWL Purdue',
    description: 'Explains what counts as plagiarism, common mistakes, and how to acknowledge sources correctly in all contexts.',
    url: 'https://owl.purdue.edu/owl/avoiding_plagiarism/index.html',
    source: 'University',
    duration: '7 min read',
    skillTags: ['citation_practice', 'ai_literacy'],
    phaseTags: [1, 2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r024',
    type: 'pdf',
    embedType: 'pdf',
    title: 'APA 7th Edition Reference Card (PDF)',
    description: 'Quick-reference card covering the most common APA 7th Edition citation formats for journals, books, and web sources.',
    url: 'https://apastyle.apa.org/instructional-aids/reference-guide.pdf',
    source: 'Journal',
    duration: '2 pages',
    skillTags: ['citation_practice'],
    phaseTags: [2, 3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r025',
    type: 'article',
    embedType: 'link',
    title: 'Academic Integrity — What Students Need to Know',
    description: 'Overview of academic integrity principles, how to cite AI tools, and institutional expectations for original work.',
    url: 'https://library.educause.edu/resources/2023/6/academic-integrity-in-the-age-of-ai',
    source: 'Journal',
    duration: '10 min read',
    skillTags: ['citation_practice', 'ai_literacy'],
    phaseTags: [1, 2, 3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── Research Skills (4) ──────────────────────────────────────
  {
    id: 'r026',
    type: 'video',
    embedType: 'youtube',
    title: 'How to Use Google Scholar Effectively',
    description: 'Demonstrates advanced Google Scholar searches, setting up alerts, finding full-text PDFs, and tracking citations.',
    url: 'https://www.youtube.com/watch?v=SqITmBgVKA4',
    source: 'YouTube',
    duration: '9 min',
    skillTags: ['research_skills', 'source_evaluation'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r027',
    type: 'article',
    embedType: 'link',
    title: 'Academic Database Search Strategies',
    description: 'A practical guide to Boolean operators, truncation, phrase searching, and filters for library database research.',
    url: 'https://owl.purdue.edu/owl/research_and_citation/conducting_research/research_overview/index.html',
    source: 'University',
    duration: '8 min read',
    skillTags: ['research_skills'],
    phaseTags: [2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r028',
    type: 'video',
    embedType: 'youtube',
    title: 'How to Write a Literature Review',
    description: 'Step-by-step guide to finding, organising, and synthesising academic sources into a coherent literature review.',
    url: 'https://www.youtube.com/watch?v=zIYC6zG265E',
    source: 'YouTube',
    duration: '13 min',
    skillTags: ['research_skills', 'evidence_use'],
    phaseTags: [3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r029',
    type: 'podcast',
    embedType: 'link',
    title: 'Methodology & Research Design — The Thesis Whisperer Podcast',
    description: 'Academic podcast exploring research design choices, methodology frameworks, and how to structure a thesis.',
    url: 'https://thesiswhisperer.com/category/podcast/',
    source: 'Podcast',
    duration: '30–45 min',
    skillTags: ['research_skills'],
    phaseTags: [4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },

  // ── AI Literacy (5) ─────────────────────────────────────────
  {
    id: 'r030',
    type: 'video',
    embedType: 'youtube',
    title: 'AI Literacy: What Every Student Should Know',
    description: 'An accessible introduction to how large language models work, their limitations, and what "hallucination" means for academic research.',
    url: 'https://www.youtube.com/watch?v=zjkBMFhNj_g',
    source: 'YouTube',
    duration: '12 min',
    skillTags: ['ai_literacy'],
    phaseTags: [1, 2, 3],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r031',
    type: 'article',
    embedType: 'link',
    title: 'Artificial Intelligence and Academic Integrity — ICAI',
    description: 'The International Center for Academic Integrity\'s policy framework for AI use in higher education assignments.',
    url: 'https://academicintegrity.org/resources/articles',
    source: 'Journal',
    duration: '10 min read',
    skillTags: ['ai_literacy', 'citation_practice'],
    phaseTags: [1, 2, 3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r032',
    type: 'article',
    embedType: 'link',
    title: 'How to Use AI Tools Without Undermining Your Learning',
    description: 'Evidence-based guidance from cognitive scientists on when AI scaffolding helps and when it hurts deep learning.',
    url: 'https://www.edweek.org/technology/how-to-use-ai-as-a-learning-tool-without-undermining-thinking/2023/09',
    source: 'Journal',
    duration: '8 min read',
    skillTags: ['ai_literacy'],
    phaseTags: [1, 2],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r033',
    type: 'article',
    embedType: 'link',
    title: 'Prompt Engineering for Students — A Practical Guide',
    description: 'Teaches how to write effective prompts for AI writing assistants, with examples of weak vs strong prompts for academic tasks.',
    url: 'https://learnprompting.org/docs/intro',
    source: 'Other',
    duration: '15 min read',
    skillTags: ['ai_literacy'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r034',
    type: 'video',
    embedType: 'youtube',
    title: 'Critical AI Evaluation: Don\'t Trust, Verify',
    description: 'Demonstrates techniques for fact-checking AI-generated content, including cross-referencing, source-tracing, and hallucination spotting.',
    url: 'https://www.youtube.com/watch?v=hJP5GqnTrNo',
    source: 'YouTube',
    duration: '10 min',
    skillTags: ['ai_literacy', 'source_evaluation'],
    phaseTags: [2, 3, 4],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
  {
    id: 'r035',
    type: 'article',
    embedType: 'link',
    title: 'The Algorithmic Feed — Reading Media Critically in 2025',
    description: 'Explores how recommendation algorithms shape what we read, and how to develop critical media literacy for algorithm-curated information.',
    url: 'https://mediamanipulation.org/definitions/algorithmic-amplification',
    source: 'Other',
    duration: '7 min read',
    skillTags: ['ai_literacy', 'critical_reading', 'source_evaluation'],
    phaseTags: [3, 4, 5],
    vetted: true,
    addedBy: 'ai',
    addedAt: '2025-01-01T00:00:00.000Z',
  },
];
