// content/units/unit08.js — Unit 8: AI Research Tools
import { quiz }        from '../../src/components/activities.js';
import { readingTask } from '../../src/components/reading-task.js';
import { visualTask }  from '../../src/components/visual-task.js';

const RT_CONFIG = {
  id: 'rt-u8', unitId: 'u8', unitNum: 8,
  title: 'Trusting AI with Your Research — How Far Is Too Far?',
  level: 'Foundation Level 4', wordTarget: 150,
  source: 'Adapted for Academic Literacies — drawing on Stokel-Walker (2023) and MIT Library AI Research Guides',
  vocab: [
    { term: 'Hallucinated citation', definition: 'A reference generated by an AI tool that appears to be a real academic source — with a plausible-sounding author, title, journal, and year — but does not actually exist.', example: 'A student asked ChatGPT for references on inclusive education in South Africa. Two of the five citations it provided were fabricated — the authors existed, but had never written those papers.' },
    { term: 'Verification workflow', definition: 'A systematic, step-by-step process a researcher follows to confirm that information from any source — including AI — is accurate and reliable before using it.', example: 'A verification workflow for AI-generated citations: copy the citation, search it in Scopus, confirm the author, title, journal, and year all match, then locate the full text.' },
    { term: 'Elicit', definition: 'An AI-powered research tool (elicit.com) that searches peer-reviewed literature and summarises findings. Unlike chatbots, Elicit only surfaces real papers with verified citations.', example: 'Elicit can identify the main findings across 20 studies on a topic — but you still need to read the papers to assess their quality.' },
    { term: 'ResearchRabbit', definition: 'A free AI tool that maps the connections between academic papers — showing which papers cite each other, what was published before, and what came after.', example: 'Starting with one key paper on early literacy, ResearchRabbit shows you the network of related research — helping you discover papers you would not have found by searching alone.' },
  ],
  text: `<h3>Trusting AI with Your Research — How Far Is Too Far?</h3>
    <p>In early 2023, a New York lawyer named Steven Schwartz submitted a legal brief citing six court cases in support of his argument. The cases were detailed, persuasive, and completely fictional. Schwartz had asked ChatGPT to help him find cases — and the AI had invented them, complete with realistic case names, courts, and dates. When the opposing lawyer and the judge tried to find the cases, they did not exist. Schwartz faced serious professional consequences. His defence: he had not known that AI could "make things up."</p>
    <p>University students face the same risk. When you ask a general AI chatbot to help you find academic sources, it may provide references that appear to be real papers — with plausible authors, titles, journals, and dates — but do not exist. This is called a hallucinated citation. The danger is not just that you submit false information. The danger is that you may not know it is false. Hallucinated citations are structurally designed to be indistinguishable from real ones without verification.</p>
    <p>The responsible use of AI for research requires a clear distinction between tools that create and tools that retrieve. Chatbots like ChatGPT create text based on patterns in training data — they are not connected to a real database of academic records. Tools like Elicit, ResearchRabbit, and Scopus AI retrieve real papers from real databases. The distinction is fundamental: a retrieval tool tells you what actually exists; a generative tool tells you what sounds like it might exist.</p>
    <p>This does not mean you should avoid chatbots entirely. They can be useful for brainstorming search terms, explaining complex concepts, and identifying broad debates in a field — as long as you verify every specific claim and every citation before use. The rule is simple: AI generates, you verify. Every time, no exceptions.</p>`,
  questions: [
    'What is a hallucinated citation and why is it particularly dangerous for a student who does not know it is false? Use the example from the text to support your explanation.',
    'The text distinguishes between tools that "create" and tools that "retrieve." Explain this distinction in your own words. Give one example of each type.',
    'The text says chatbots can still be useful for research — but only in specific ways. What are those ways, and what is the non-negotiable rule that must accompany any chatbot use for academic work?',
  ],
  writingPrompt: `You are helping a fellow student who asked ChatGPT for five references for their assignment on "play-based learning in Grade R classrooms in South Africa." ChatGPT gave them five detailed, well-formatted citations.
Write 4–5 sentences advising them: What should they do before using any of these references? Walk them through your verification workflow step by step. Which tool(s) would you recommend for checking? What should they do if one citation turns out not to exist?`,
};

const VT_CONFIG = {
  id: 'vt-u8', unitId: 'u8',
  title: 'Reading a Bar Chart: AI Tool Usage Among Students',
  chartType: 'bar chart',
  visualDescription: 'A horizontal bar chart showing percentage of university students using different AI tools for academic work, with a note about verification rates',
  source: 'Illustrative data constructed for Academic Literacies — based on patterns from JISC (2023) Student Digital Experience Insights Survey',
  observePrompt: 'Study this bar chart carefully. Look at both the bar lengths AND the additional data point in the note. Notice which tools are most popular and what the note reveals about student behaviour.',
  observeChecklist: [
    'The six AI tools listed on the y-axis',
    'What the x-axis measures (read the label carefully)',
    'Which tool is most used, and which is least used',
    'The important note below the chart about verification',
  ],
  visual: `<div style="padding:20px;background:#fff;border-radius:12px;border:1px solid var(--border);">
    <div style="font-size:16px;font-weight:700;color:var(--navy);margin-bottom:4px;text-align:center;">AI Tool Usage for Academic Research</div>
    <div style="font-size:12px;color:var(--muted);text-align:center;margin-bottom:20px;">% of university students reporting using each tool for academic work (n=2,847)</div>
    <div style="display:flex;flex-direction:column;gap:12px;">
      ${[
        ['ChatGPT', 73, '#ef4444'],
        ['Google Scholar', 68, '#22c55e'],
        ['Gemini / Copilot', 41, '#f97316'],
        ['Wikipedia (as start)', 38, '#eab308'],
        ['Elicit / Semantic Scholar', 12, '#6366f1'],
        ['Scopus / Web of Science', 9, '#3b82f6'],
      ].map(([label, val, color]) => `
        <div style="display:flex;align-items:center;gap:12px;">
          <div style="min-width:160px;font-size:13px;font-weight:600;text-align:right;">${label}</div>
          <div style="flex:1;background:#f1f5f9;border-radius:99px;height:28px;position:relative;overflow:hidden;">
            <div style="position:absolute;left:0;top:0;height:100%;width:${val}%;background:${color};border-radius:99px;display:flex;align-items:center;justify-content:flex-end;padding-right:8px;">
              <span style="color:#fff;font-weight:700;font-size:12px;">${val}%</span>
            </div>
          </div>
        </div>`).join('')}
    </div>
    <div style="margin-top:16px;padding:12px 16px;background:#fef3c7;border-radius:8px;border:1px solid #fde68a;font-size:13px;">
      <strong>⚠️ Note:</strong> Of students who reported using ChatGPT or Gemini for references, only <strong>23%</strong> reported verifying those citations in an academic database before submitting.
    </div>
    <div style="font-size:11px;color:var(--muted);margin-top:8px;text-align:center;font-style:italic;">Illustrative data based on JISC (2023) Student Digital Experience Insights Survey patterns</div>
  </div>`,
  questions: [
    { q: 'The chart shows that ChatGPT (73%) is far more popular for academic research than Scopus (9%). Given what you know about hallucinated citations, what does this gap represent in terms of academic risk across a student population?', hint: 'Think about scale: if 73% of students use ChatGPT for references, and most do not verify...', modelAnswer: 'The gap represents a large-scale academic integrity risk. If 73% of students use ChatGPT for references and only 23% verify those citations (as shown in the note), it means roughly 56% of students are potentially submitting unverified — possibly hallucinated — citations. At a university of 20,000 students, this could mean thousands of assignments per year containing false references. This is not individual misconduct — it is a systemic gap between how students use AI and what academic integrity requires.' },
    { q: 'The note at the bottom is arguably more important than the bars themselves. What does the 23% verification rate tell you that the usage bars alone cannot?', hint: 'The bars show what tools students use. The note shows what students do AFTER using them.', modelAnswer: 'The bars only tell us about usage frequency — they say nothing about how critically students engage with the outputs. The 23% verification rate reveals that the majority of students using generative AI for citations are trusting the output without checking it. This is the critical gap: the risk of hallucinated citations is not theoretical — it is actively manifesting in student work because the behaviour gap (use without verify) is widespread.' },
    { q: 'Elicit and Scopus are the most academically reliable tools in this context but have the lowest usage rates (12% and 9%). What are two possible explanations for this pattern, and what would need to change to increase their use?', hint: 'Think about access, awareness, and perceived difficulty.', modelAnswer: 'Two explanations: (1) Awareness — many students may not know these tools exist or understand their advantages over ChatGPT. (2) Access and perceived difficulty — Scopus requires institutional login and students may find its interface less intuitive than a chatbot. To increase use: explicit teaching of these tools in academic literacy modules (as this unit does), mandatory use for certain assignments, and library induction sessions that make the access pathway clear.' },
  ],
};

export const unit08 = {
  id: 'u8', badge: 'Unit 8', title: 'AI Research Tools: Possibilities & Pitfalls',
  phase: 'Phase 2 — Finding & Evaluating Knowledge',
  html: () => `
    <h1>Unit 8: AI Research Tools — Possibilities & Pitfalls</h1>
    <p class="lead">AI can help you find, map, and understand research faster than ever. It can also silently fabricate sources that do not exist. This unit gives you the framework to use AI research tools powerfully — and without academic risk.</p>
    <div class="unit-outcomes"><div class="outcomes-label">By the end of this unit you will be able to:</div><ul>
      <li>Distinguish AI retrieval tools (safe to cite) from generative AI tools (verify everything)</li>
      <li>Identify a hallucinated citation and explain exactly how to detect one</li>
      <li>Read a bar chart to extract patterns and interpret a critical data note</li>
      <li>Write a clear explanation of responsible AI research use for a fellow student</li>
    </ul></div>
    <div class="section-label">🎬 Watch First</div>
    <p>This library tutorial demonstrates how AI tools like Elicit and ResearchRabbit work in practice. Notice the difference between how these tools work and how a chatbot works — that difference is everything.</p>
    <div id="ivp-unit8" data-video-key="unit8" class="ivp-container"></div>
    ${quiz('q8a','You use Elicit to find papers on teacher burnout. It returns 8 papers with citations. You ask ChatGPT the same question and it also returns 8 papers. What is the critical difference?',['ChatGPT results are more recent than Elicit results','Elicit retrieves real papers from a verified database; ChatGPT generates text that may include fabricated citations','Elicit only searches SA journals; ChatGPT searches globally','There is no meaningful difference — both search academic databases'],1,'✅ Elicit retrieves from a real academic database — those papers exist. ChatGPT generates text based on training data patterns — some citations will be real, some hallucinated. You cannot tell the difference without verifying each one in Scopus or Google Scholar.')}
    ${quiz('q8b','How do you verify whether a ChatGPT-provided citation is real?',['Ask ChatGPT to confirm the citation is accurate','Search the exact title in Scopus or Google Scholar and verify that author, journal, year, and content all match','Check that the journal name sounds legitimate','Search the author name on Google'],1,'✅ The only reliable verification is searching the exact title in Scopus or Google Scholar and confirming every detail. Do not ask ChatGPT to verify its own output — it will confidently confirm a hallucination.')}
    <h2>📊 Visual Activity: Reading a Bar Chart</h2>
    <p>Bar charts appear throughout academic research papers and policy documents. This activity develops your ability to read beyond the bars themselves — and to notice what data notes reveal that the chart cannot.</p>
    ${visualTask('vt-u8', VT_CONFIG)}
    <h2>Reading & Writing Activity</h2>
    ${readingTask('rt-u8', RT_CONFIG)}
    <div class="unit-closing"><div class="unit-closing-label">Before You Move On</div>
    <p>"AI generates. You verify. Every time, no exceptions. This is not a burden — it is the definition of being a responsible researcher."</p></div>`,
};
